# Generated by Django 2.0.2 on 2018-02-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_album_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.CharField(blank=True, max_length=30, verbose_name='장르'),
        ),
        migrations.AddField(
            model_name='album',
            name='released_date',
            field=models.DateField(blank=True, null=True, verbose_name='발매일'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=50, verbose_name='앨범명'),
        ),
    ]
