# Generated by Django 2.0.2 on 2018-02-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_remove_album_artists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='released_date',
        ),
        migrations.AddField(
            model_name='album',
            name='melon_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='멜론 Album ID'),
        ),
        migrations.AddField(
            model_name='album',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='img_cover',
            field=models.ImageField(blank=True, upload_to='album', verbose_name='커버 이미지'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=100, verbose_name='앨범명'),
        ),
    ]
